<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>(//input[@id='nomor-hp-atau-email'])[1]</description>
   <name>nomor-hp-atau-email_Input</name>
   <tag></tag>
   <elementGuidId>5749b13b-0d33-40f2-9f13-d20d10f024d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='nomor-hp-atau-email'])[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
